### ISSUE TITLE
Latest master branch doesn't have a tag version

### ISSUE THREAD

**Issue by jwarykowski** [yinlinchen/amplify-preview-actions#17]
**Describe the bug**

The latest master branch version does not have an associated tag and therefore when using `yinlinchen/amplify-preview-actions@v1.1` you don't get the latest version of the codebase.

If possible can you tag and push the latest version of master?

**Comment by yinlinchen** [comment]
@jwarykowski Thanks for letting me know. Please see https://github.com/yinlinchen/amplify-preview-actions/releases/tag/v1.2
