### ISSUE TITLE
How to find BackendEnvARN from AWS Console

### ISSUE THREAD

**Issue by daltonfury42** [yinlinchen/amplify-preview-actions#2]
Hi @yinlinchen 

Can you tell me where I can find the backend ARN. Thanks.

**Comment by yinlinchen** [comment]
@daltonfury42 You can use below command
```
aws amplify list-backend-environments --app-id=AmplifyAppId
```
Doc: [list-backend-environments](https://docs.aws.amazon.com/cli/latest/reference/amplify/list-backend-environments.html)

**Comment by daltonfury42** [comment]
Thanks
