### ISSUE TITLE
Cutting of branch name to 10 characters

### ISSUE THREAD

**Issue by daltonfury42** [yinlinchen/amplify-preview-actions#3]
In the readme, I can see that the branch name is cut short to 10 chracters:

```
        echo "##[set-output name=setbranchname;]$(echo ${GITHUB_HEAD_REF} | cut -c-10)"
```

Curious to know why this is required. It was giving me issues. If the branch name is greater than 10 characters, amplify is supplied the truncated name, and it then complains that branch does not exist.

**Comment by yinlinchen** [comment]
Hi @daltonfury42 It is not a required. You can remove ```| cut -c-10``` from your workflow. I use our workflow for an example, we use JIRA ticket# as our PR branch name, and it always less that 10 characters. You can totally control what you would like to have in your ```workflow.yml```.  I will update that basic ```workflow.yml``` example later in the readme. Thanks for the feedback.

**Comment by daltonfury42** [comment]
Understood. I have piggybacked removing this from the readme as part if #4
