### ISSUE TITLE
Minimal IAM Permissions

### ISSUE THREAD

**Issue by sean-smith** [yinlinchen/amplify-preview-actions#5]
In the [README](https://github.com/yinlinchen/amplify-preview-actions#iam-roles--mfa-for-aws-amplify) you link to the [Amplify IAM Docs](https://docs.amplify.aws/cli/usage/iam#n3-set-up-the-local-development-environment-dev-corp) which have an example of the needed IAM permissions to do everything with amplify. Basically an Amplify Admin Policy.

I'd like to see what are the minimal necessary permissions to create the Pull Request preview. My initial thinking is it look like:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AmplifyPreviewURL",
            "Effect": "Allow",
            "Action": [
                "amplify:ListApps",
                "amplify:ListBranches",
                "amplify:ListDomainAssociations",
                "amplify:GetApp",
                "amplify:CreateBranch",
                "amplify:DeleteBranch",
                "amplify:UpdateApp",
                "amplify:CreateApp",
            ],
            "Resource": "[ARN of Amplify Deployment]"
        }
    ]
}
```

**Comment by yinlinchen** [comment]
Hi @sean-smith 

Thanks for pointing this out. Please see below for the minimal necessary permissions to create the Pull Request preview. I will update readme at the later time today. 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "amplify:StartJob",
            "Resource": "arn:aws:amplify:${Region}:${Account}:apps/{AppId}/branches/*/jobs/*"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "amplify:DeleteBranch",
                "amplify:CreateBranch"
            ],
            "Resource": "arn:aws:amplify:${Region}:${Account}:apps/{AppId}/branches/*"
        }
    ]
}
```

**Comment by yinlinchen** [comment]
https://github.com/yinlinchen/amplify-preview-actions/commit/fd354df21899cfc7fea6a8b564326bc609842e1f Readme is updated.

**Comment by sean-smith** [comment]
You're the best! While I've got you, how should I go about debugging / testing the feature as a whole?

**Comment by yinlinchen** [comment]
Hi @sean-smith 

You can see the action files here: 
1. [Pull request](https://github.com/yinlinchen/bookapp/blob/master/.github/workflows/pr.yml)
2. [Merge or close](https://github.com/yinlinchen/bookapp/blob/master/.github/workflows/close.yml)

Live example: https://github.com/yinlinchen/bookapp/pulls

Note that for the PR, first label PR with `Ready for review` and then assign to a reviewer and it will trigger GitHub actions and you can see the logs in [action log](https://github.com/yinlinchen/bookapp/runs/1114214854?check_suite_focus=true), for example.

**Comment by sean-smith** [comment]
Thanks @yinlinchen 

Couple more suggestions:

1. The Github Secrets are all uppercased, so providing them as uppercase in the examples would be helpful.
2. `GITHUB_TOKEN` for some reason wasn't allowed for me. I had to use GITHUBTOKEN instead. I don't know if this is something specific for my organization or broader.

Here's what I've changed. See https://github.com/aws-samples/aws-hpc-tutorials/pull/21 for an example
```yaml
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        AmplifyAppId: ${{ secrets.AMPLIFYAPPID }}
        BackendEnvARN: ${{ secrets.BACKENDENVARN }}
        AWS_REGION: 'us-east-1'
```

**Comment by sean-smith** [comment]
Should I enabled PR previews?

i.e. 
![image](https://user-images.githubusercontent.com/5545980/93276611-df217400-f774-11ea-8a70-36c336f0ca6d.png)

**Comment by yinlinchen** [comment]
@sean-smith Thanks for the suggestion, I updated the readme. https://github.com/yinlinchen/amplify-preview-actions/commit/bb739b369fe498b8b286e6e4d2188841ec482278 

GitHub automatically creates a `GITHUB_TOKEN` secret to use in your workflow. You can use it directly, see [About the GITHUB_TOKEN secret](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret)

You don't need to enable PR previews in the Amplify console.

**Comment by sean-smith** [comment]
Thanks! Really great tool

On Sep 15, 2020, at 6:22 PM, Yinlin Chen <notifications@github.com> wrote:

﻿

@sean-smith<https://github.com/sean-smith> Thanks for the suggestion, I updated the readme. bb739b3<https://github.com/yinlinchen/amplify-preview-actions/commit/bb739b369fe498b8b286e6e4d2188841ec482278>

GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow. You can use it directly, see About the GITHUB_TOKEN secret<https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret>

You don't need to enable PR previews in the Amplify console.

**Comment by sean-smith** [comment]
How do you get the BackendEnvARN? Is this the same as the `App Arn` shown in the console?

![image](https://user-images.githubusercontent.com/5545980/93383905-2a8d5e00-f819-11ea-821d-2407c5fcea4b.png)

**Update**

This is definitely not the right arn to use as I got:

> An error occurred (BadRequestException) when calling the CreateBranch operation: Backend environment arn is not valid

**Comment by yinlinchen** [comment]
@sean-smith Please see https://github.com/yinlinchen/amplify-preview-actions/issues/2

**Comment by sean-smith** [comment]
Thanks @yinlinchen 

I've opened https://github.com/yinlinchen/amplify-preview-actions/pull/6 to clarify these parameters.

**Comment by sean-smith** [comment]
I think we can close this now. Thanks @yinlinchen for answering all my questions, really appreciate it!
